version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bigdata_lab1_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bigdata_lab1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/source:/csv
      - ./source_table.sql:/docker-entrypoint-initdb.d/01_source_table.sql
      - ./load_data.sql:/docker-entrypoint-initdb.d/02_load_data.sql
      - ./DDL.sql:/docker-entrypoint-initdb.d/03_ddl.sql
      - ./DML.sql:/docker-entrypoint-initdb.d/04_dml.sql

volumes:
  postgres_data: